name: ai_multitasker
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.2
  provider: ^6.0.3
  google_generative_ai: ^0.4.3
  intl:
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  get: ^4.6.6
  path_provider: ^2.1.3
  flutter_sound: ^9.7.2
  flutter_file_dialog: ^3.0.2
  contacts_service: ^0.6.3
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.3.0
  pdf: ^3.11.0
  open_file: ^3.3.2
  dash_chat_2: ^0.0.20
  flutter_gemini: ^2.0.3
  path_provider_windows: ^2.3.0
  mime: ^1.0.5
  flutter_rating_bar: ^4.0.0
  flashy_tab_bar2: ^0.0.10
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.68.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/chatbot.jpeg
    - assets/interview.jpeg
    - assets/code.jpeg
    - assets/note.jpeg
    - assets/assistent.jpeg
    - assets/vocabulary.jpeg
    - assets/voice.jpeg
    - assets/profile_placeholder.jpeg
    - assets/s.jpg
    - assets/instagram.png
    - assets/credly.png
    - assets/github.png
    - assets/linkedin.png
    - assets/notepad.png
    - assets/notepad2.png
    - assets/facebook.png
    - assets/cloud.png
    - assets/notepad3.png
    - assets/notepad4.png
    - assets/gfg.png
    - assets/star.jpg
